platform :ios, '13.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://cdn.cocoapods.org/'

use_frameworks! :linkage => :static

def shared_pods
  pod 'Firebase/Core', '10.12.0'
  pod 'Firebase/Auth', '10.12.0'
  pod 'Firebase/Firestore', '10.12.0'
  pod 'Firebase/Analytics', '10.12.0'
  pod 'ElevenLabs-iOS-SDK', '1.0.0'
  pod 'RunwayML-iOS', '1.2.0'
end

target 'FantasyGMAssistant' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true
  )

  shared_pods

  target 'FantasyGMAssistantTests' do
    inherit! :complete
  end

  pod 'SwiftLint', '0.52.0', :configurations => ['Debug']
end

post_install do |installer|
  react_native_post_install(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      
      if target.name == "React-Core.common-AccessibilityResources"
        target.remove_from_project
      end
    end
  end
  
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
    aggregate_target.user_project.save
  end
end